[build]
  publish = "build"
  command = "pip install -r requirements.txt && python build.py"

[dev]
  command = "flask run"
  port = 5000

[functions]
  directory = "functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200
